### ISSUE TITLE
convert_construction_year()がエラー吐く

### ISSUE THREAD

**Issue by Nurkic** [Nurkic/probspace_realestate#23]
self.df = self.convert_construction_year()←ここで詰まる
df["建築年"] = df["建築年"].str.replace("戦前", "昭和20年")←ここ
ValueError: cannot reindex from a duplicate axis←エラー文

ちなみに# self.df = self.convert_construction_year()とした上で再度sklearns.pyを実行したらちゃんと動いたのでこの関数のみが問題かと！
時間あるときに直してもらえると助かります...
最新版のsklearns.pyも上げておきます

**Comment by Kattsuuya** [comment]
僕の環境では同じエラーが出ないです:_(
下のコードを実行してみたのですが，正常終了しました．
もう少し原因を探ってみます．．．

```Python
import pandas as pd
from package import preprocess

df_train = pd.read_csv("input/train_data.csv")
df_train_tmp = preprocess.Preprocessor(df_train).all("label")
print(df_train_tmp.info())
```

**Comment by Nurkic** [comment]
迅速な対応ありがとう！
まじかー
testの方でエラー出るってことはない？
testも大丈夫だったら、trainからyの列を除いてからtestとconcatしたデータフレームを作って、それでも通るか試してみてほしい！

**Comment by Kattsuuya** [comment]
連結したあとのDataFrameに対してエラーが出るみたいです．．．
実装の仕方変えてみます😅

**Comment by Nurkic** [comment]
なるほどね！
とりあえず原因がわかってよかった、よろしくお願いします！
