### ISSUE TITLE
特徴量の時間がかかっちゃう問題

### ISSUE THREAD

**Issue by Nurkic** [Nurkic/probspace_realestate#25]
まずモデルの説明。今使用している機械学習のパッケージ「optgbm」ってやつなんだけれども、これはざっくりいうと
「ベースの機械学習モデルはlightGBMで、モデルのハイパーパラメータをoptunaっていうパラメータ自動チューニングパッケージで最適化する」
ってことを中身でやっているもの。
lightGBMはハイパラめちゃ種類多いし、optuna自分でコード書くのやや面倒だから、OptGBMは非常に便利なんだけれども、如何せんコード回るのに時間がかかるんだよね...
次に、特徴量選択の話になるんだけども、具体的に何をやっているかというと、
1. 空のリストselected宣言, best_score = 99999.0とする
2. trainに含まれる特徴量のうちランダムにとってきた特徴量aを使ってモデルを学習、バリデーションデータで予測、精度評価
3. 精度がbest_scoreを下回れば、best_scoreを更新し、特徴量aをselectedに加える
4. trainに含まれる特徴量のうち、特徴量a以外の特徴量bを選び、2-3を繰り返す
5. 全ての特徴量が終了したら、selectedリストに入った特徴量を残す
ということをやっている。しかし、これをoptgbmでやってしまうと、2.のたびにわざわざパラメータ最適化が内部で回るため、すごく時間がかかる。（まあやってもいいけど笑）
そのため今は普通のlightGBMで特徴量選択を行い、選ばれた特徴量を使ってoptgbmを学習させる、ということをしているんだけど、これだと厳密とは言えない。なんか他にいい手があれば教えてほしい！

**Comment by Nurkic** [comment]
せめて研究室のGPUで回せれば早いんだろうか...

**Comment by Kattsuuya** [comment]
2つ質問があります！

1. この特徴量選択の1〜5ってfeature_selection.pyで実装していただいたGreedy Forward Selectionのことであってますか？
2. この実装方法は，ランダムに選んだ特徴量単体でモデルを作成して，その精度が良いかどうかでその時選んだ特徴量を採用するか判断するということだと思いますが，これだと特徴量の中で単体で使用したときに一番フィットする特徴量がたまたま最初に選ばれてしまったときはbest_scoreがそれ以降更新されないので特徴量が1つしか選ばれないということになりませんか．
