### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by Nurkic** [Nurkic/probspace_realestate#33]
エラー個所:203行目
df["延床面積（㎡）"] = df["延床面積（㎡）"].mask(df["延床面積（㎡）"].isnull(), df["面積（㎡）"] * df["容積率（％）"] / 100)

エラー文:TypeError: can't multiply sequence by non-int of type 'float'

多分容積率がfloatゆえにエラー出てる
（sequenceに対してはintしか掛け算できないらしい、np.multiplyならfloatもokみたいな記事あって試したけどそれでもダメだった）
一応for文を使った同じ内容を実装してコメントアウトしてあリマス。mask使いつつエラー解消できそうなら直してもらえるとありがたい...

**Comment by Kattsuuya** [comment]
すみません😭
検証不足でした．
すぐに修正します！
