### ISSUE TITLE
カテゴリカルな特徴量の扱い

### ISSUE THREAD

**Issue by Nurkic** [Nurkic/probspace_realestate#4]
カテゴリカルな特徴量についてなんだけど、使用する機械学習モデルによってone_hotな表現にした方が良い場合とそうでない場合（例えば、決定木ベースのLightGBMやRandomForestはone_hotな表現にせずひとつの特徴量として扱い、カラムの型を"category"として扱った方が良いとdocumentに書いてある）があるため、最終的にモデルをアンサンブルするときのことを考えると関数が2パターンあるといいかも、と思いました！ちなみにone_hotにしない場合の処理はCategoryEncoderクラスでほぼ賄えるはず！

**Comment by Kattsuuya** [comment]
建物の構造に関しては"ＲＣ、木造"のように複数になっているものがありましたが，これはこれで1つのカテゴリと考えるということですか？

**Comment by Nurkic** [comment]
複数の情報が含まれている場合は難しいとこだよね笑
"RC、木造"みたいな単語の組み合わせをひとつのカテゴリとして考えると、単語のパターンが多いと単語同士の組み合わせが多すぎて、ラベルの種類が増えすぎてしまう気がする...
ニューラルネットならonehot推奨だからonehotで問題ないんだけど、決定木ベースのモデルを使う場合は
1. 出現回数の少ない単語同士の組み合わせをまとめてひとつのラベルにしてしまう
2. 1.を行なった上で、one_hotな表現にした場合とそうでない場合でそれぞれクロスバリデーションを行い、精度が良かった方を採用する
っていうので良い気がする！

**Comment by Kattsuuya** [comment]
了解しました！

**Comment by Nurkic** [comment]
あざ！
