### ISSUE TITLE
データのデータのimportおよび提出用csvのexport

### ISSUE THREAD

**Issue by Nurkic** [Nurkic/probspace_realestate#5]
pytest用のコードを書いていてふと思ったけどデータはどうやってimportしようか？普通にデータローカルに持ってきてimportするだけなら簡単だけどWebからスクレイピングで取得できるようなコードをかく？csvの提出は結局ローカルからやるしかないしローカルからimportでもいいかなて思っているんだけど...

**Comment by Kattsuuya** [comment]
ファイルサイズがMBオーダーで大きいので，ローカルからimportするのでいいと思います！

**Comment by Nurkic** [comment]
了解！じゃそこは各々ローカルにcsvを落とすということで！
